// Generated by CoffeeScript 1.9.0
(function() {
  var CryptoJS, IconButton, Panel, Request, ToggleButton, button, changed, currentTime, firefoxStorage, panel, self, tabs, _;

  self = require('sdk/self');

  tabs = require("sdk/tabs");

  firefoxStorage = require("sdk/simple-storage");

  Panel = require("sdk/panel").Panel;

  ToggleButton = require("sdk/ui/button/toggle").ToggleButton;

  IconButton = require("sdk/ui/button/action").ActionButton;

  Request = require("sdk/request").Request;

  CryptoJS = require("./vendor/CryptoJS").CryptoJS;

  _ = require('./vendor/Underscore1-8-3');

  console.log('CryptoJS.SHA512("adfasdf")');

  console.log(CryptoJS.SHA512("adfasdf"));

  console.log(_.pick({
    name: 'moe',
    age: 50,
    userid: 'moe1'
  }, 'name'));

  console.log('console.log tabs.activeTab');

  console.log(tabs.activeTab.readyState);

  console.log(tabs.activeTab);

  Request({
    url: 'https://hn.algolia.com/api/v1/search?query=elon&tags=story',
    onComplete: function(response) {
      console.log('onComplete: (response) ->');
      console.debug(response.json);
      return console.log(response.json);
    }
  }).get();

  currentTime = Date.now();

  button = IconButton({
    id: "kiwi-button",
    label: "Kiwi Conversations",
    badge: 0,
    badgeColor: "#00AAAA",
    icon: {
      "16": "./kiwiFavico16.png",
      "32": "./kiwiFavico32.png",
      "64": "./kiwiFavico64.png"
    },
    onClick: function(state) {
      console.log("button '" + state.label + "' was clicked");
      return changed(state);
    }
  });

  tabs.on('ready', function(tab) {
    return console.log('tab is loaded', tab.title, tab.url);
  });

  firefoxStorage.storage.myArray = [1, 1, 2, 3, 5, 8, 13];

  firefoxStorage.storage.myBoolean = true;

  firefoxStorage.storage.myNull = null;

  firefoxStorage.storage.myNumber = 3.1337;

  firefoxStorage.storage.myObject = {
    a: "foo",
    b: {
      c: true
    },
    d: null
  };

  firefoxStorage.storage.myString = "O day!";

  changed = function(state) {
    button.badge = state.badge + 1;
    if (state.checked) {
      button.badgeColor = "#AA00AA";
    } else {
      button.badgeColor = "#00AAAA";
    }
    return panel.show();
  };

  panel = Panel({
    width: 500,
    height: 500,
    contentURL: "./test.html",
    contentScriptFile: './KiwiPopup.js'
  });

  panel.port.on("click-link", function(url) {
    return console.log(url);
  });

}).call(this);
