// Generated by CoffeeScript 1.9.0
(function() {
  var ActionButton, Panel, ToggleButton, button, changed, firefoxStorage, myScript, panel, self, tabs;

  self = require('sdk/self');

  tabs = require("sdk/tabs");

  firefoxStorage = require("sdk/simple-storage");

  Panel = require("sdk/panel").Panel;

  ToggleButton = require("sdk/ui/button/toggle").ToggleButton;

  ActionButton = require("sdk/ui/button/action").ActionButton;

  button = ActionButton({
    id: "my-button",
    label: "my button",
    badge: 0,
    badgeColor: "#00AAAA",
    icon: {
      "16": "./kiwiFavico16.png",
      "32": "./kiwiFavico32.png",
      "64": "./kiwiFavico64.png"
    },
    onClick: function(state) {
      console.log("button '" + state.label + "' was clicked");
      return changed(state);
    }
  });

  tabs.on('ready', function(tab) {
    return console.log('tab is loaded', tab.title, tab.url);
  });

  firefoxStorage.storage.myArray = [1, 1, 2, 3, 5, 8, 13];

  firefoxStorage.storage.myBoolean = true;

  firefoxStorage.storage.myNull = null;

  firefoxStorage.storage.myNumber = 3.1337;

  firefoxStorage.storage.myObject = {
    a: "foo",
    b: {
      c: true
    },
    d: null
  };

  firefoxStorage.storage.myString = "O day!";

  changed = function(state) {
    button.badge = state.badge + 1;
    if (state.checked) {
      button.badgeColor = "#AA00AA";
    } else {
      button.badgeColor = "#00AAAA";
    }
    if (button.badge % 2 === 0) {
      return panel.show();
    } else {
      return panel.hide();
    }
  };

  myScript = "window.addEventListener('click', function(event) { var t = event.target; if (t.nodeName == 'A') self.port.emit('click-link', t.toString()); }, false);";

  panel = Panel({
    width: 180,
    height: 180,
    contentURL: "https://en.wikipedia.org/w/index.php?title=Jetpack&useformat=mobile",
    contentScript: myScript
  });

  panel.port.on("click-link", function(url) {
    return console.log(url);
  });

}).call(this);
